import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import {
  AlertPrompt,
  LoginFormikContainer,
  RegisterFormikContainer,
} from "../components";
import { useAppContext } from "../context/appContext";

const Home: React.FC = () => {
  const [activeTab, setActiveTab] = useState<"login" | "register">("login");
  const { user, alert } = useAppContext();
  const router = useRouter();

  // todo: useEffects
  // ? if logged in send to chat page
  useEffect(() => {
    if (user) {
      router.push("/chat");
    }
  }, [user]);

  // todo: functions
  if (user) {
    return null;
  }

  return (
    <div className="login-pg w-screen h-screen bg-primary flex justify-center bg-no-repeat bg-cover">
      {alert && <AlertPrompt message={alert} />}
      <Head>
        <title>Chatty - The MERN Chat </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
